name: Holiii jijiji

on:
  push:
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "hola mundo"

      - name: Descargar código
        uses: actions/checkout@v4

      - name: En qué carpeta estoy
        run: pwd

      - name: listado de archivos
        run: ls -la
      
      - name: instalar node
        run: actions/setup@v4

      - name: verificar node
        run: node --version