name: Holiii jijiji

on:
  push:
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "hola mundo"

      - name: Descargar código
        uses: actions/checkout@v4

      - name: En qué carpeta estoy
        run: pwd

      - name: Listado de archivos
        run: ls -la

      - name: Instalar Node
        uses: actions/setup-node@v4
        with:
          node-version: 20

      - name: Verificar Node
        run: node --version

      - name: Verificar npm
        run: npm --version

      - name: Inicializar proyecto
        run: npm init -y

      - name: Instalar ESLint
        run: npm install --save-dev eslint @eslint/js globals