name: Holiii jijiji

on:
  push:
  workflow_dispatch:

jobs:
  hola:
    runs-on: ubuntu-latest
    steps:
      - name: Saludar
        run: echo "hola mundo"
      - name: Descargar código
        run: actions/checkout@v4
      - name: en qué carpeta estoy
        run: pwd